use_frameworks!

target 'SwiftPTV_Example' do
  pod 'SwiftPTV', :path => '../'

  target 'SwiftPTV_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
